//
// File generated by /opt/root/bin/rootcint at Thu Aug  3 11:55:34 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME mktreedstchain_sct_fitABCCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mktreedstchain_sct_fitABCCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ASYFadcPeak_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ASYFadcPeak(void *p = 0);
   static void *newArray_ASYFadcPeak(Long_t size, void *p);
   static void delete_ASYFadcPeak(void *p);
   static void deleteArray_ASYFadcPeak(void *p);
   static void destruct_ASYFadcPeak(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ASYFadcPeak*)
   {
      ::ASYFadcPeak *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ASYFadcPeak >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ASYFadcPeak", ::ASYFadcPeak::Class_Version(), "./mktreedstchain_sct_fitABC.hxx", 118,
                  typeid(::ASYFadcPeak), DefineBehavior(ptr, ptr),
                  &::ASYFadcPeak::Dictionary, isa_proxy, 4,
                  sizeof(::ASYFadcPeak) );
      instance.SetNew(&new_ASYFadcPeak);
      instance.SetNewArray(&newArray_ASYFadcPeak);
      instance.SetDelete(&delete_ASYFadcPeak);
      instance.SetDeleteArray(&deleteArray_ASYFadcPeak);
      instance.SetDestructor(&destruct_ASYFadcPeak);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ASYFadcPeak*)
   {
      return GenerateInitInstanceLocal((::ASYFadcPeak*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ASYFadcPeak*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void ASYEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ASYEvent(void *p = 0);
   static void *newArray_ASYEvent(Long_t size, void *p);
   static void delete_ASYEvent(void *p);
   static void deleteArray_ASYEvent(void *p);
   static void destruct_ASYEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ASYEvent*)
   {
      ::ASYEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ASYEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ASYEvent", ::ASYEvent::Class_Version(), "./mktreedstchain_sct_fitABC.hxx", 199,
                  typeid(::ASYEvent), DefineBehavior(ptr, ptr),
                  &::ASYEvent::Dictionary, isa_proxy, 4,
                  sizeof(::ASYEvent) );
      instance.SetNew(&new_ASYEvent);
      instance.SetNewArray(&newArray_ASYEvent);
      instance.SetDelete(&delete_ASYEvent);
      instance.SetDeleteArray(&deleteArray_ASYEvent);
      instance.SetDestructor(&destruct_ASYEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ASYEvent*)
   {
      return GenerateInitInstanceLocal((::ASYEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ASYEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *ASYFadcPeak::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ASYFadcPeak::Class_Name()
{
   return "ASYFadcPeak";
}

//______________________________________________________________________________
const char *ASYFadcPeak::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ASYFadcPeak*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ASYFadcPeak::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ASYFadcPeak*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ASYFadcPeak::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ASYFadcPeak*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ASYFadcPeak::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ASYFadcPeak*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *ASYEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ASYEvent::Class_Name()
{
   return "ASYEvent";
}

//______________________________________________________________________________
const char *ASYEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ASYEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ASYEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ASYEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ASYEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ASYEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ASYEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ASYEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void ASYFadcPeak::Streamer(TBuffer &R__b)
{
   // Stream an object of class ASYFadcPeak.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ASYFadcPeak::Class(),this);
   } else {
      R__b.WriteClassBuffer(ASYFadcPeak::Class(),this);
   }
}

//______________________________________________________________________________
void ASYFadcPeak::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ASYFadcPeak.
      TClass *R__cl = ::ASYFadcPeak::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mod", &mod);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pds0", &pds0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdr0", &pdr0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tls0", &tls0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tlo0", &tlo0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tm0", &tm0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "am0", &am0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "at0", &at0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pds1", &pds1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdr1", &pdr1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tls1", &tls1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tlo1", &tlo1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tm1", &tm1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "am1", &am1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "at1", &at1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pds2", &pds2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdr2", &pdr2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tls2", &tls2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tlo2", &tlo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tm2", &tm2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "am2", &am2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "at2", &at2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sam0", &sam0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sat0", &sat0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sam1", &sam1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sat1", &sat1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sam2", &sam2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sat2", &sat2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p00", &p00);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p04", &p04);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p05", &p05);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p06", &p06);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p09", &p09);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rc0", &rc0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p10", &p10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p12", &p12);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p13", &p13);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p14", &p14);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p15", &p15);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p16", &p16);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p17", &p17);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p18", &p18);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p19", &p19);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p110", &p110);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rc1", &rc1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p20", &p20);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p22", &p22);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p23", &p23);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p24", &p24);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p25", &p25);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p26", &p26);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p27", &p27);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p28", &p28);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p29", &p29);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p210", &p210);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rc2", &rc2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi20", &chi20);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi21", &chi21);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi22", &chi22);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ASYFadcPeak(void *p) {
      return  p ? new(p) ::ASYFadcPeak : new ::ASYFadcPeak;
   }
   static void *newArray_ASYFadcPeak(Long_t nElements, void *p) {
      return p ? new(p) ::ASYFadcPeak[nElements] : new ::ASYFadcPeak[nElements];
   }
   // Wrapper around operator delete
   static void delete_ASYFadcPeak(void *p) {
      delete ((::ASYFadcPeak*)p);
   }
   static void deleteArray_ASYFadcPeak(void *p) {
      delete [] ((::ASYFadcPeak*)p);
   }
   static void destruct_ASYFadcPeak(void *p) {
      typedef ::ASYFadcPeak current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ASYFadcPeak

//______________________________________________________________________________
void ASYEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class ASYEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ASYEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(ASYEvent::Class(),this);
   }
}

//______________________________________________________________________________
void ASYEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ASYEvent.
      TClass *R__cl = ::ASYEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "run", &run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evt", &evt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "npeak", &npeak);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "HADC[32]", HADC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "HTDC[32]", HTDC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PADC[32]", PADC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PTDC[32]", PTDC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*peak", &peak);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ASYEvent(void *p) {
      return  p ? new(p) ::ASYEvent : new ::ASYEvent;
   }
   static void *newArray_ASYEvent(Long_t nElements, void *p) {
      return p ? new(p) ::ASYEvent[nElements] : new ::ASYEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_ASYEvent(void *p) {
      delete ((::ASYEvent*)p);
   }
   static void deleteArray_ASYEvent(void *p) {
      delete [] ((::ASYEvent*)p);
   }
   static void destruct_ASYEvent(void *p) {
      typedef ::ASYEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ASYEvent

/********************************************************
* mktreedstchain_sct_fitABCCint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemktreedstchain_sct_fitABCCint();

extern "C" void G__set_cpp_environmentmktreedstchain_sct_fitABCCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("mktreedstchain_sct_fitABC.hxx");
  G__cpp_reset_tagtablemktreedstchain_sct_fitABCCint();
}
#include <new>
extern "C" int G__cpp_dllrevmktreedstchain_sct_fitABCCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ASYFadcPeak */
static int G__mktreedstchain_sct_fitABCCint_807_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ASYFadcPeak* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ASYFadcPeak[n];
     } else {
       p = new((void*) gvp) ASYFadcPeak[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ASYFadcPeak;
     } else {
       p = new((void*) gvp) ASYFadcPeak;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ASYFadcPeak::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ASYFadcPeak::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ASYFadcPeak::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ASYFadcPeak::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ASYFadcPeak*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ASYFadcPeak::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ASYFadcPeak::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ASYFadcPeak::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_807_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ASYFadcPeak::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mktreedstchain_sct_fitABCCint_807_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ASYFadcPeak* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ASYFadcPeak(*(ASYFadcPeak*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ASYFadcPeak G__TASYFadcPeak;
static int G__mktreedstchain_sct_fitABCCint_807_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ASYFadcPeak*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ASYFadcPeak*) (soff+(sizeof(ASYFadcPeak)*i)))->~G__TASYFadcPeak();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ASYFadcPeak*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ASYFadcPeak*) (soff))->~G__TASYFadcPeak();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mktreedstchain_sct_fitABCCint_807_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ASYFadcPeak* dest = (ASYFadcPeak*) G__getstructoffset();
   *dest = *(ASYFadcPeak*) libp->para[0].ref;
   const ASYFadcPeak& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* ASYEvent */
static int G__mktreedstchain_sct_fitABCCint_808_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ASYEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ASYEvent[n];
     } else {
       p = new((void*) gvp) ASYEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ASYEvent;
     } else {
       p = new((void*) gvp) ASYEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((ASYEvent*) G__getstructoffset())->AddPeak());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const ASYEvent*) G__getstructoffset())->Peak((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ASYEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ASYEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ASYEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ASYEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ASYEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ASYEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ASYEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ASYEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mktreedstchain_sct_fitABCCint_808_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ASYEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mktreedstchain_sct_fitABCCint_808_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ASYEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ASYEvent(*(ASYEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ASYEvent G__TASYEvent;
static int G__mktreedstchain_sct_fitABCCint_808_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ASYEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ASYEvent*) (soff+(sizeof(ASYEvent)*i)))->~G__TASYEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ASYEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ASYEvent*) (soff))->~G__TASYEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mktreedstchain_sct_fitABCCint_808_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ASYEvent* dest = (ASYEvent*) G__getstructoffset();
   *dest = *(ASYEvent*) libp->para[0].ref;
   const ASYEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ASYFadcPeak */

/* ASYEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmktreedstchain_sct_fitABCCint {
 public:
  G__Sizep2memfuncmktreedstchain_sct_fitABCCint(): p(&G__Sizep2memfuncmktreedstchain_sct_fitABCCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmktreedstchain_sct_fitABCCint::*p)();
};

size_t G__get_sizep2memfuncmktreedstchain_sct_fitABCCint()
{
  G__Sizep2memfuncmktreedstchain_sct_fitABCCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemktreedstchain_sct_fitABCCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak))) {
     ASYFadcPeak *G__Lderived;
     G__Lderived=(ASYFadcPeak*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak),G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent))) {
     ASYEvent *G__Lderived;
     G__Lderived=(ASYEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent),G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemktreedstchain_sct_fitABCCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ASYFadcPeak */
static void G__setup_memvarASYFadcPeak(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak));
   { ASYFadcPeak *p; p=(ASYFadcPeak*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->mod)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mod=",0,"module number [0-34]");
   G__memvar_setup((void*)((long)(&p->pds0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pds0=",0,"baseline");
   G__memvar_setup((void*)((long)(&p->pdr0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pdr0=",0,"baseline rms");
   G__memvar_setup((void*)((long)(&p->tls0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tls0=",0,"=tail inv. slope -> from fit of exp(-t/tail+offset) to the tail of the waveform");
   G__memvar_setup((void*)((long)(&p->tlo0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tlo0=",0,"=tail offset");
   G__memvar_setup((void*)((long)(&p->tm0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tm0=",0,"raw time offset, beginning of the pulse (for PD0)");
   G__memvar_setup((void*)((long)(&p->am0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"am0=",0,"raw amplitude for PD0");
   G__memvar_setup((void*)((long)(&p->at0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"at0=",0,"raw position of maximum");
   G__memvar_setup((void*)((long)(&p->pds1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pds1=",0,"baseline");
   G__memvar_setup((void*)((long)(&p->pdr1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pdr1=",0,"baseline rms");
   G__memvar_setup((void*)((long)(&p->tls1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tls1=",0,"=tail inv. slope -> from fit of exp(-t/tail+offset) to the tail of the waveform");
   G__memvar_setup((void*)((long)(&p->tlo1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tlo1=",0,"=tail offset");
   G__memvar_setup((void*)((long)(&p->tm1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tm1=",0,"raw time offset, beginning of the pulse (for PD0)");
   G__memvar_setup((void*)((long)(&p->am1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"am1=",0,"raw amplitude for PD0");
   G__memvar_setup((void*)((long)(&p->at1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"at1=",0,"raw position of maximum");
   G__memvar_setup((void*)((long)(&p->pds2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pds2=",0,"baseline");
   G__memvar_setup((void*)((long)(&p->pdr2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pdr2=",0,"baseline rms");
   G__memvar_setup((void*)((long)(&p->tls2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tls2=",0,"=tail inv. slope -> from fit of exp(-t/tail+offset) to the tail of the waveform");
   G__memvar_setup((void*)((long)(&p->tlo2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tlo2=",0,"=tail offset");
   G__memvar_setup((void*)((long)(&p->tm2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tm2=",0,"raw time offset, beginning of the pulse (for PD0)");
   G__memvar_setup((void*)((long)(&p->am2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"am2=",0,"raw amplitude for PD0");
   G__memvar_setup((void*)((long)(&p->at2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"at2=",0,"raw position of maximum");
   G__memvar_setup((void*)((long)(&p->sam0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sam0=",0,"amplitude");
   G__memvar_setup((void*)((long)(&p->sat0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sat0=",0,"position of maximum - absolute - wrt 0");
   G__memvar_setup((void*)((long)(&p->sam1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sam1=",0,"amplitude");
   G__memvar_setup((void*)((long)(&p->sat1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sat1=",0,"position of maximum - absolute - wrt 0");
   G__memvar_setup((void*)((long)(&p->sam2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sam2=",0,"amplitude");
   G__memvar_setup((void*)((long)(&p->sat2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sat2=",0,"position of maximum - absolute - wrt 0");
   G__memvar_setup((void*)((long)(&p->p00)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p00=",0,"amplitude of Si component in PD0");
   G__memvar_setup((void*)((long)(&p->p04)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p04=",0,"time offset (from fit) for PD0");
   G__memvar_setup((void*)((long)(&p->p05)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p05=",0,"fall time of Si component in PD0");
   G__memvar_setup((void*)((long)(&p->p06)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p06=",0,"undershoot time");
   G__memvar_setup((void*)((long)(&p->p09)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p09=",0,"rise time of Si component in PD0");
   G__memvar_setup((void*)((long)(&p->rc0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rc0=",0,"rc in PD0");
   G__memvar_setup((void*)((long)(&p->p10)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p10=",0,"amplitude of Si component in PD1");
   G__memvar_setup((void*)((long)(&p->p12)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p12=",0,"amplitude of Fast CsI(Tl) in PD1 ");
   G__memvar_setup((void*)((long)(&p->p13)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p13=",0,"amplitude of Slow CsI(Tl) in PD1 ");
   G__memvar_setup((void*)((long)(&p->p14)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p14=",0,"time offset (from fit) for PD1 ");
   G__memvar_setup((void*)((long)(&p->p15)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p15=",0,"fall time of Si component in PD1");
   G__memvar_setup((void*)((long)(&p->p16)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p16=",0,"undershoot time");
   G__memvar_setup((void*)((long)(&p->p17)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p17=",0,"fall time of Fast CsI(Tl) in PD1 ");
   G__memvar_setup((void*)((long)(&p->p18)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p18=",0,"fall time of Slow CsI(Tl) in PD1 ");
   G__memvar_setup((void*)((long)(&p->p19)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p19=",0,"rise time of Si component in PD1");
   G__memvar_setup((void*)((long)(&p->p110)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p110=",0,"rise time of CsI(Tl) in PD1");
   G__memvar_setup((void*)((long)(&p->rc1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rc1=",0,"rc in PD1");
   G__memvar_setup((void*)((long)(&p->p20)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p20=",0,"p2* -> same as p1* but for PD2");
   G__memvar_setup((void*)((long)(&p->p22)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p22=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p23)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p23=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p24)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p24=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p25)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p25=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p26)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p26=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p27)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p27=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p28)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p28=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p29)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p29=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p210)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p210=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rc2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rc2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chi20)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"chi20=",0,"chi2 in PD0");
   G__memvar_setup((void*)((long)(&p->chi21)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"chi21=",0,"chi2 in PD1");
   G__memvar_setup((void*)((long)(&p->chi22)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"chi22=",0,"chi2 in PD2");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* ASYEvent */
static void G__setup_memvarASYEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent));
   { ASYEvent *p; p=(ASYEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"run=",0,"run number");
   G__memvar_setup((void*)((long)(&p->evt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"evt=",0,"event number");
   G__memvar_setup((void*)((long)(&p->npeak)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeak=",0,"multiplicity of peaks");
   G__memvar_setup((void*)((long)(&p->HADC)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"HADC[32]=",0,"HECTOR ADC");
   G__memvar_setup((void*)((long)(&p->HTDC)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"HTDC[32]=",0,"HECTOR TDC");
   G__memvar_setup((void*)((long)(&p->PADC)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"PADC[32]=",0,"HECTOR ADC");
   G__memvar_setup((void*)((long)(&p->PTDC)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"PTDC[32]=",0,"HECTOR TDC");
   G__memvar_setup((void*)((long)(&p->peak)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClonesArray),-1,-1,1,"peak=",0,"->");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmktreedstchain_sct_fitABCCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncASYFadcPeak(void) {
   /* ASYFadcPeak */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak));
   G__memfunc_setup("ASYFadcPeak",988,G__mktreedstchain_sct_fitABCCint_807_0_1, 105, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__mktreedstchain_sct_fitABCCint_807_0_3, 85, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ASYFadcPeak::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mktreedstchain_sct_fitABCCint_807_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ASYFadcPeak::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mktreedstchain_sct_fitABCCint_807_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ASYFadcPeak::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mktreedstchain_sct_fitABCCint_807_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ASYFadcPeak::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mktreedstchain_sct_fitABCCint_807_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mktreedstchain_sct_fitABCCint_807_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ASYFadcPeak::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mktreedstchain_sct_fitABCCint_807_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ASYFadcPeak::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mktreedstchain_sct_fitABCCint_807_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ASYFadcPeak::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mktreedstchain_sct_fitABCCint_807_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ASYFadcPeak::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ASYFadcPeak", 988, G__mktreedstchain_sct_fitABCCint_807_0_15, (int) ('i'), G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak), -1, 0, 1, 1, 1, 0, "u 'ASYFadcPeak' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ASYFadcPeak", 1114, G__mktreedstchain_sct_fitABCCint_807_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mktreedstchain_sct_fitABCCint_807_0_17, (int) ('u'), G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak), -1, 1, 1, 1, 1, 0, "u 'ASYFadcPeak' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncASYEvent(void) {
   /* ASYEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent));
   G__memfunc_setup("ASYEvent",751,G__mktreedstchain_sct_fitABCCint_808_0_1, 105, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddPeak",650,G__mktreedstchain_sct_fitABCCint_808_0_3, 85, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak), -1, 0, 0, 1, 1, 0, "", "Setup Peak", (void*) NULL, 0);
   G__memfunc_setup("Peak",385,G__mktreedstchain_sct_fitABCCint_808_0_4, 85, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - n", "Get Peak", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__mktreedstchain_sct_fitABCCint_808_0_5, 85, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ASYEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mktreedstchain_sct_fitABCCint_808_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ASYEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mktreedstchain_sct_fitABCCint_808_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ASYEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mktreedstchain_sct_fitABCCint_808_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ASYEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mktreedstchain_sct_fitABCCint_808_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mktreedstchain_sct_fitABCCint_808_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ASYEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mktreedstchain_sct_fitABCCint_808_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ASYEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mktreedstchain_sct_fitABCCint_808_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ASYEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mktreedstchain_sct_fitABCCint_808_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ASYEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ASYEvent", 751, G__mktreedstchain_sct_fitABCCint_808_0_17, (int) ('i'), G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent), -1, 0, 1, 1, 1, 0, "u 'ASYEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ASYEvent", 877, G__mktreedstchain_sct_fitABCCint_808_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mktreedstchain_sct_fitABCCint_808_0_19, (int) ('u'), G__get_linked_tagnum(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent), -1, 1, 1, 1, 1, 0, "u 'ASYEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmktreedstchain_sct_fitABCCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmktreedstchain_sct_fitABCCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmktreedstchain_sct_fitABCCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak = { "ASYFadcPeak" , 99 , -1 };
G__linked_taginfo G__mktreedstchain_sct_fitABCCintLN_ASYEvent = { "ASYEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemktreedstchain_sct_fitABCCint() {
  G__mktreedstchain_sct_fitABCCintLN_TClass.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TBuffer.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMemberInspector.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TObject.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TClonesArray.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak.tagnum = -1 ;
  G__mktreedstchain_sct_fitABCCintLN_ASYEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemktreedstchain_sct_fitABCCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_ASYFadcPeak),sizeof(ASYFadcPeak),-1,292096,"A peak segment",G__setup_memvarASYFadcPeak,G__setup_memfuncASYFadcPeak);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mktreedstchain_sct_fitABCCintLN_ASYEvent),sizeof(ASYEvent),-1,292096,"Event structure",G__setup_memvarASYEvent,G__setup_memfuncASYEvent);
}
extern "C" void G__cpp_setupmktreedstchain_sct_fitABCCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupmktreedstchain_sct_fitABCCint()");
  G__set_cpp_environmentmktreedstchain_sct_fitABCCint();
  G__cpp_setup_tagtablemktreedstchain_sct_fitABCCint();

  G__cpp_setup_inheritancemktreedstchain_sct_fitABCCint();

  G__cpp_setup_typetablemktreedstchain_sct_fitABCCint();

  G__cpp_setup_memvarmktreedstchain_sct_fitABCCint();

  G__cpp_setup_memfuncmktreedstchain_sct_fitABCCint();
  G__cpp_setup_globalmktreedstchain_sct_fitABCCint();
  G__cpp_setup_funcmktreedstchain_sct_fitABCCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmktreedstchain_sct_fitABCCint();
  return;
}
class G__cpp_setup_initmktreedstchain_sct_fitABCCint {
  public:
    G__cpp_setup_initmktreedstchain_sct_fitABCCint() { G__add_setup_func("mktreedstchain_sct_fitABCCint",(G__incsetup)(&G__cpp_setupmktreedstchain_sct_fitABCCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmktreedstchain_sct_fitABCCint() { G__remove_setup_func("mktreedstchain_sct_fitABCCint"); }
};
G__cpp_setup_initmktreedstchain_sct_fitABCCint G__cpp_setup_initializermktreedstchain_sct_fitABCCint;

