//
// File generated by rootcint at Wed Aug 23 21:41:35 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME KR_Cint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "KR_Cint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void KRAnal_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void KRAnal_Dictionary();
   static void *new_KRAnal(void *p = 0);
   static void *newArray_KRAnal(Long_t size, void *p);
   static void delete_KRAnal(void *p);
   static void deleteArray_KRAnal(void *p);
   static void destruct_KRAnal(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KRAnal*)
   {
      ::KRAnal *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::KRAnal),0);
      static ::ROOT::TGenericClassInfo 
         instance("KRAnal", "./KRAnal.h", 20,
                  typeid(::KRAnal), DefineBehavior(ptr, ptr),
                  0, &KRAnal_Dictionary, isa_proxy, 0,
                  sizeof(::KRAnal) );
      instance.SetNew(&new_KRAnal);
      instance.SetNewArray(&newArray_KRAnal);
      instance.SetDelete(&delete_KRAnal);
      instance.SetDeleteArray(&deleteArray_KRAnal);
      instance.SetDestructor(&destruct_KRAnal);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KRAnal*)
   {
      return GenerateInitInstanceLocal((::KRAnal*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KRAnal*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KRAnal_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::KRAnal*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_KRAnal(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KRAnal : new ::KRAnal;
   }
   static void *newArray_KRAnal(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KRAnal[nElements] : new ::KRAnal[nElements];
   }
   // Wrapper around operator delete
   static void delete_KRAnal(void *p) {
      delete ((::KRAnal*)p);
   }
   static void deleteArray_KRAnal(void *p) {
      delete [] ((::KRAnal*)p);
   }
   static void destruct_KRAnal(void *p) {
      typedef ::KRAnal current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KRAnal

/********************************************************
* KR_Cint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableKR_Cint();

extern "C" void G__set_cpp_environmentKR_Cint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("KRAnal.h");
  G__add_compiledheader("myClass.h");
  G__add_compiledheader("utility.h");
  G__cpp_reset_tagtableKR_Cint();
}
#include <new>
extern "C" int G__cpp_dllrevKR_Cint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* KRAnal */
static int G__KR_Cint_825_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KRAnal* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KRAnal((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) KRAnal((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new KRAnal[n];
       } else {
         p = new((void*) gvp) KRAnal[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new KRAnal;
       } else {
         p = new((void*) gvp) KRAnal;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__KR_CintLN_KRAnal));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KR_Cint_825_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KRAnal*) G__getstructoffset())->Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KR_Cint_825_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KRAnal*) G__getstructoffset())->Loop((Char_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KR_Cint_825_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((KRAnal*) G__getstructoffset())->ReadLine((FILE*) G__int(libp->para[0]), (char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KR_Cint_825_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KRAnal*) G__getstructoffset())->SetWriteTree((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KR_Cint_825_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KRAnal*) G__getstructoffset())->SetEnergy((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__KR_Cint_825_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KRAnal* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KRAnal(*(KRAnal*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__KR_CintLN_KRAnal));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KRAnal G__TKRAnal;
static int G__KR_Cint_825_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KRAnal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KRAnal*) (soff+(sizeof(KRAnal)*i)))->~G__TKRAnal();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KRAnal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KRAnal*) (soff))->~G__TKRAnal();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__KR_Cint_825_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KRAnal* dest = (KRAnal*) G__getstructoffset();
   *dest = *(KRAnal*) libp->para[0].ref;
   const KRAnal& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* KRAnal */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncKR_Cint {
 public:
  G__Sizep2memfuncKR_Cint(): p(&G__Sizep2memfuncKR_Cint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncKR_Cint::*p)();
};

size_t G__get_sizep2memfuncKR_Cint()
{
  G__Sizep2memfuncKR_Cint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceKR_Cint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__KR_CintLN_KRAnal))) {
     KRAnal *G__Lderived;
     G__Lderived=(KRAnal*)0x1000;
     {
       myClass *G__Lpbase=(myClass*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__KR_CintLN_KRAnal),G__get_linked_tagnum(&G__KR_CintLN_myClass),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableKR_Cint() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__KR_CintLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KR_CintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KR_CintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__KR_CintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* KRAnal */
static void G__setup_memvarKRAnal(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__KR_CintLN_KRAnal));
   { KRAnal *p; p=(KRAnal*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TFile),-1,-1,4,"theOut=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,G__defined_typename("Char_t"),-1,4,"theOutFileName[64]=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"WriteTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"Pen=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TFile),-1,-1,4,"f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->a0_1)-(long)(p)),102,0,0,-1,-1,-1,1,"a0_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->a1_1)-(long)(p)),102,0,0,-1,-1,-1,1,"a1_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->a2_1)-(long)(p)),102,0,0,-1,-1,-1,1,"a2_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tls0_1)-(long)(p)),102,0,0,-1,-1,-1,1,"tls0_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p14_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p14_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p04_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p04_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p24_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p24_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p10_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p10_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p12_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p12_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p13_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p13_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p20_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p20_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p22_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p22_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p23_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p23_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mod_1)-(long)(p)),105,0,0,-1,-1,-1,1,"mod_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->evnb)-(long)(p)),105,0,0,-1,-1,-1,1,"evnb=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p0_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p0_1[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p1_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p1_1[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p2_1)-(long)(p)),102,0,0,-1,-1,-1,1,"p2_1[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p0_2)-(long)(p)),102,0,0,-1,-1,-1,1,"p0_2[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p1_2)-(long)(p)),102,0,0,-1,-1,-1,1,"p1_2[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p2_2)-(long)(p)),102,0,0,-1,-1,-1,1,"p2_2[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->enCsI1)-(long)(p)),102,0,0,-1,-1,-1,1,"enCsI1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->enCsI2)-(long)(p)),102,0,0,-1,-1,-1,1,"enCsI2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hamp01)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hamp01[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hamp12)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hamp12[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hamp01Cut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hamp01Cut[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hamp12Cut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hamp12Cut[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp12_p13)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp12_p13[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp22_p23)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp22_p23[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp10_p12p13)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp10_p12p13[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp10_enProt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp10_enProt[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp10_p12p13st)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp10_p12p13st[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp10_p12p13stCut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp10_p12p13stCut[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp10_p12p13c)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp10_p12p13c[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp20_p22p23)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH2F),-1,-1,1,"hp20_p22p23[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->htm1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"htm1[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hpdr1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hpdr1[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hchi21)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hchi21[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hpds1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hpds1[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp22p23)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hp22p23[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp22p23c)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hp22p23c[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp12p13)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hp12p13[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hp12p13c)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hp12p13c[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hen_prot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TH1F),-1,-1,1,"hen_prot[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cutg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TCutG),-1,-1,1,"cutg[16]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cutg1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TCutG),-1,-1,1,"cutg1[16]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cutg2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TCutG),-1,-1,1,"cutg2[16]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fcut1_mod14)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TCutG),-1,-1,1,"fcut1_mod14=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fcut2_mod5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TCutG),-1,-1,1,"fcut2_mod5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TGraph),-1,-1,1,"gr[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->c1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_TCanvas),-1,-1,1,"c1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p14min)-(long)(p)),102,0,0,-1,-1,-1,1,"p14min[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p14max)-(long)(p)),102,0,0,-1,-1,-1,1,"p14max[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p24min)-(long)(p)),102,0,0,-1,-1,-1,1,"p24min[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p24max)-(long)(p)),102,0,0,-1,-1,-1,1,"p24max[20]=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarKR_Cint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncKRAnal(void) {
   /* KRAnal */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__KR_CintLN_KRAnal));
   G__memfunc_setup("OpenGeometry",1246,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 4, 0, "", "Gets the geometry information", (void*) NULL, 0);
   G__memfunc_setup("CreateHistos",1230,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WriteHistos",1157,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KRAnal",537,G__KR_Cint_825_0_4, 105, G__get_linked_tagnum(&G__KR_CintLN_KRAnal), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__KR_Cint_825_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Loop",410,G__KR_Cint_825_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Char_t' 0 - file", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadLine",772,G__KR_Cint_825_0_7, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"E - - 0 - fID C - - 0 - line", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWriteTree",1223,G__KR_Cint_825_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - f", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__KR_Cint_825_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - en", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("KRAnal", 537, G__KR_Cint_825_0_10, (int) ('i'), G__get_linked_tagnum(&G__KR_CintLN_KRAnal), -1, 0, 1, 1, 1, 0, "u 'KRAnal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KRAnal", 663, G__KR_Cint_825_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__KR_Cint_825_0_12, (int) ('u'), G__get_linked_tagnum(&G__KR_CintLN_KRAnal), -1, 1, 1, 1, 1, 0, "u 'KRAnal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncKR_Cint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
   G__memvar_setup((void*)(&gKRA),85,0,0,G__get_linked_tagnum(&G__KR_CintLN_KRAnal),-1,-1,1,"gKRA=",0,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalKR_Cint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcKR_Cint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__KR_CintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__KR_CintLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TCutG = { "TCutG" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_myClass = { "myClass" , 99 , -1 };
G__linked_taginfo G__KR_CintLN_KRAnal = { "KRAnal" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableKR_Cint() {
  G__KR_CintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__KR_CintLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__KR_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__KR_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KR_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__KR_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__KR_CintLN_TFile.tagnum = -1 ;
  G__KR_CintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TH1F.tagnum = -1 ;
  G__KR_CintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TH2F.tagnum = -1 ;
  G__KR_CintLN_TTree.tagnum = -1 ;
  G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__KR_CintLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__KR_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KR_CintLN_TCanvas.tagnum = -1 ;
  G__KR_CintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__KR_CintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KR_CintLN_TGraph.tagnum = -1 ;
  G__KR_CintLN_TCutG.tagnum = -1 ;
  G__KR_CintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__KR_CintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__KR_CintLN_myClass.tagnum = -1 ;
  G__KR_CintLN_KRAnal.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableKR_Cint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__KR_CintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TFile);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TH1F);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TH2F);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TTree);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TGraph);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TCutG);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__KR_CintLN_myClass);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__KR_CintLN_KRAnal),sizeof(KRAnal),-1,1280,(char*)NULL,G__setup_memvarKRAnal,G__setup_memfuncKRAnal);
}
extern "C" void G__cpp_setupKR_Cint(void) {
  G__check_setup_version(30051515,"G__cpp_setupKR_Cint()");
  G__set_cpp_environmentKR_Cint();
  G__cpp_setup_tagtableKR_Cint();

  G__cpp_setup_inheritanceKR_Cint();

  G__cpp_setup_typetableKR_Cint();

  G__cpp_setup_memvarKR_Cint();

  G__cpp_setup_memfuncKR_Cint();
  G__cpp_setup_globalKR_Cint();
  G__cpp_setup_funcKR_Cint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncKR_Cint();
  return;
}
class G__cpp_setup_initKR_Cint {
  public:
    G__cpp_setup_initKR_Cint() { G__add_setup_func("KR_Cint",(G__incsetup)(&G__cpp_setupKR_Cint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initKR_Cint() { G__remove_setup_func("KR_Cint"); }
};
G__cpp_setup_initKR_Cint G__cpp_setup_initializerKR_Cint;

